# put info here
require_relative "../config/environment.rb"


10.times do
User.create(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, weight: Random.rand(80..300))
end

Workout.create(name: "Ultimate Ab Workout" , duration: 15, description: "Works out your obliques and upper and lower abs. For when you only have 15 minutes to get it done. ")
Workout.create(name: "Complete Upper Body Workout", duration: 30, description: " Concentrates on your chest, shoulders, and back." )
Workout.create(name: "Do You Even Squat", duration:45, description:"Different variations of squats, lunges, and gluteus maximus Workout" )
Workout.create(name: "SpongeBob Anchor Arms", duration: 25, description: "You've been spongebob anchor arms. Now do the workout that helped him achieve those amazing resuls!!!" )
Workout.create(name: "Gain Hops Workout", duration: 20 , description: "Contains multiple HIIT to help you get that extra inch when hooping." )
Workout.create(name: "Summer Bod in 6 weeks", duration:45, description: "Full body workout alternating different days to get ready for that summer." )
Workout.create(name: "30 Minute Arms", duration: 32, description: "Got 32 minutes? Get buff arms fast.")
Workout.create(name: "Body Pump", duration: 20, description: "Get your body moving with easy cardio execises!")
Workout.create(name: "Action Hero Workout", duration: 45, description: "Go from zero to hero with this intense full body workout.")
Workout.create(name: "Baby got back?", duration: 32, description: "Get your back muscles twerking with some wholesome back execises.")
Workout.create(name: "Shoulder Tone", duration: 32, description: "Build good form with these shoulder Exercise.") #adding data to Exercises
Exercise.create(name: "Barbell Hack Squats", reps: 10 , sets: 3, category: "Legs")
Exercise.create(name: "Barbell Lunges", reps: 10 , sets: 3, category: "Legs")
Exercise.create(name: "Braced Squat", reps: 10 , sets: 3, category: "Legs")
Exercise.create(name: "Bulgarian Split Squat", reps: 12, category: "Legs")
Exercise.create(name: "Dumbbell Goblet Squat", reps: 12, category: "Legs")
Exercise.create(name: "Dumbbell Lunges Standing", reps: 12 , sets: 3, category: "Legs")
Exercise.create(name: "Dumbbell Lunges Walking", reps: 12 , sets: 3, category: "Legs")
Exercise.create(name: "Front Squats", reps: 8 , sets: 3, category: "Legs")
Exercise.create(name: "Glute Bridge", reps: 12 , sets: 3, category: "Legs")
Exercise.create(name: "Good Mornings", reps: 8 , sets: 3, category: "Legs") # #cardio Exercises
Exercise.create(name: "Bear Crawls", sets: 3, duration: 1, category: "Cardio")
Exercise.create(name: "Running", duration: 2, category: "Cardio")
Exercise.create(name: "Pre-Jog", duration: 5, category: "Cardio")
Exercise.create(name: "Sprints", duration: 0.5, category: "Cardio")
Exercise.create(name: "Bicycle", reps: 8 , sets: 3, category: "Cardio")
Exercise.create(name: "Rowing", duration: 5, category: "Cardio")
Exercise.create(name: "Walking", duration: 3, category: "Cardio")
Exercise.create(name: "Hurdles", reps: 8 , sets: 3, category: "Cardio")
Exercise.create(name: "Jumping Jacks", reps: 20 , sets: 4, category: "Cardio") # #Chest Exercises
Exercise.create(name: "Bear Walk", sets: 4, duration: 1, category: "Chest")
Exercise.create(name: "Bench Press", reps: 12, sets: 4, category: "Chest")
Exercise.create(name: "Bench Press Dumbbells", reps: 8, sets: 4, category: "Chest")
Exercise.create(name: "Butterfly", reps: 10, sets: 4, category: "Chest")
Exercise.create(name: "Butterfly Narrow Grip", reps: 10, sets: 3, category: "Chest")
Exercise.create(name: "Cable Cross-Over", reps: 8, sets: 4, category: "Chest")
Exercise.create(name: "Decline Bench Press Dumbbell", reps: 12, sets: 4, category: "Chest")
Exercise.create(name: "Fly w/ Cable", reps: 12, sets: 4, category: "Chest")
Exercise.create(name: "Fly w/ Dumbbells", reps: 12, sets: 2, category: "Chest")
Exercise.create(name: "Incline Bench Press", reps: 10, sets: 4, category: "Chest")
Exercise.create(name: "Incline Dumbbell Press", reps: 8, sets: 5, category: "Chest") #abs
Exercise.create(name: "2 Handed Kettlebell Swing", reps: 15, sets: 4, category: "Abs")
Exercise.create(name: "Barbell Ab Rollout", reps: 10, sets: 5, category: "Abs")
Exercise.create(name: "Cable Woodchoppers", reps: 15, sets: 4, category: "Abs")
Exercise.create(name: "Crunches", reps: 15, sets: 5, category: "Abs")
Exercise.create(name: "Crunches With Cable", reps: 15, sets: 4, category: "Abs")
Exercise.create(name: "Flutter Kicks", reps: 15, sets: 4, category: "Abs")
Exercise.create(name: "Hanging Leg Raises", reps: 10, sets: 3, category: "Abs")
Exercise.create(name: "Hollow Hold", sets: 3, duration: 1, category: "Abs")
Exercise.create(name: "L Hold", sets: 5, duration: 1, category: "Abs")
Exercise.create(name: "Leg Raises", sets: 5, duration: 2, category: "Abs")
Exercise.create(name: "Negative Crunches", reps: 20, sets: 3, category: "Abs")
Exercise.create(name: "Planks", sets: 5, duration: 2, category: "Abs")
Exercise.create(name: "Side Plank", sets: 4, duration: 2, category: "Abs")
Exercise.create(name: "Sit-ups", reps: 10, sets: 5, category: "Abs")
Exercise.create(name: "Trunk Rotation with Cable", reps: 15, sets: 5, category: "Abs")
Exercise.create(name: "Turkish Get-Up", reps: 20, sets: 3, category: "Abs") #Shoulders
Exercise.create(name: "Arnold Shoulder Press", reps: 11, sets: 3, category: "Shoulders")
Exercise.create(name: "Bend High Pulls", reps: 11, sets: 3, category: "Shoulders")
Exercise.create(name: "Butterfly Reverse", reps: 11, sets: 3, category: "Shoulders")
Exercise.create(name: "Shoulder Press Dumbbell", reps: 11, sets: 3, category: "Shoulders")
Exercise.create(name: "Face Pull", reps: 11, sets: 3, category: "Shoulders")
Exercise.create(name: "Front Raises", reps: 11, sets: 3, category: "Shoulders")
Exercise.create(name: "Lateral Raises", reps: 11, sets: 3, category: "Shoulders")
Exercise.create(name: "Military Press", reps: 11, sets: 3, category: "Shoulders")
Exercise.create(name: "Power Clean", reps: 11, sets: 3, category: "Shoulders")
Exercise.create(name: "Push Press", reps: 11, sets: 3, category: "Shoulders")
Exercise.create(name: "Shoulder Press Barbell", reps: 11, sets: 3, category: "Shoulders")
Exercise.create(name: "Shoulder Press, on Multi Press", reps: 11, sets: 3, category: "Shoulders")
Exercise.create(name: "Reat Delt Raises", reps: 11, sets: 3, category: "Shoulders")
Exercise.create(name: "Shrugs", reps: 11, sets: 3, category: "Shoulders") #back
Exercise.create(name: "Bent Over Barbell Row", reps: 15, sets: 3, category: "Back")
Exercise.create(name: "Bent Over Rowing", reps: 20, sets: 3, category: "Back")
Exercise.create(name: "Bent Over Rowing Reversw", reps: 20, sets: 3, category: "Back")
Exercise.create(name: "Chin-ups", reps: 10, sets: 4, category: "Back")
Exercise.create(name: "Close-grip Lat Pull Down", reps: 20, sets: 3, category: "Back")
Exercise.create(name: "Deadlifts", reps: 10, sets: 3, category: "Back")
Exercise.create(name: "Deficit Deadlift", reps: 10, sets: 3, category: "Back")
Exercise.create(name: "Hip Raises", reps: 10, sets: 3, category: "Back")
Exercise.create(name: "Incline Dumbbell Row", reps: 5, sets: 2, category: "Back")
Exercise.create(name: "Lat Pull Down", reps: 10, sets: 2, category: "Back")
Exercise.create(name: "Long-Pulley", reps: 10, sets: 5, category: "Back")
Exercise.create(name: "Pendelay Rows", reps: 15, sets: 5, category: "Back")
Exercise.create(name: "Rack Deadlift", reps: 10, sets: 5, category: "Back")
Exercise.create(name: "Superman", reps: 10, sets: 3, category: "Back")
Exercise.create(name: "V-Bar Pulldown", reps: 15, sets: 2, category: "Back") #arms
Exercise.create(name: "Axe Hold", reps: 10, sets: 5, category: "Arms")
Exercise.create(name: "Barbell Triceps Extension", reps: 10, sets: 3, category: "Arms")
Exercise.create(name: "Bench Press Narrow Grip", reps: 15, sets: 2, category: "Arms")
Exercise.create(name: "Biceps Curls With Cable", reps: 8, sets: 5, category: "Arms")
Exercise.create(name: "Bicep Curls With Barbell", reps: 8, sets: 5, category: "Arms")
Exercise.create(name: "Bicep Curls With Dumbell", reps: 8, sets: 5, category: "Arms")
Exercise.create(name: "Biceps Curls With SZ-bar", reps: 8, sets: 5, category: "Arms")
Exercise.create(name: "Body-Ups", reps: 10, sets: 3, category: "Arms")
Exercise.create(name: "Close-grip Bench Press", reps: 15, sets: 3, category: "Arms")
Exercise.create(name: "Deadhang", sets: 5, duration: 2, category: "Arms")
Exercise.create(name: "Dips", reps: 10, sets: 5, category: "Arms")
Exercise.create(name: "Dumbbell Incline Curl", reps: 8, sets: 5, category: "Arms")
Exercise.create(name: "French Press", reps: 10, sets: 4, category: "Arms")
Exercise.create(name: "Hammercurls", reps: 10, sets: 5, category: "Arms")
Exercise.create(name: "Military Press", reps: 15, sets: 5, category: "Arms")
Exercise.create(name: "Pike Push Ups", reps: 20, sets: 3, category: "Arms")
Exercise.create(name: "Preacher Curls", reps: 8, sets: 5, category: "Arms")
Exercise.create(name: "Push Ups", reps: 15, sets: 4, category: "Arms")
Exercise.create(name: "Seated Triceps Press", reps: 10, sets: 3, category: "Arms")
Exercise.create(name: "Tricep Bench Press One Dumbell", reps: 15, sets: 4, category: "Arms")
Exercise.create(name: "Tricep Dips", reps: 20, sets: 3, category: "Arms")
Exercise.create(name: "Wall Pushup", reps: 10, sets: 5, category: "Arms")
# #
#
